### PR TITLE
Fixes issue with Cancel button where after one use it would no longer work as intended

### LINKED ISSUE #34: Cancel button doesn't clear songs right after cancelling a previous time
**Describe the bug**

**To Reproduce**
1. Go to solo page
2. Add a song to your playlist
3. press cancel
4. add a song to your playlist (same or different, happens both ways)
5. press cancel
6. cancel button will disappear, song will still be there

**Expected behavior**
The cancel button should clear edits made every time it is pressed

### PR DESCRIPTION
**Pull request by MattGrantUMich**
- Fixes issue where after using the cancel button once, it would not work as intended past that

Not sure I can explain why this is the method needed, but perhaps Javascript had some weird pointer magic happening behind the scenes. Regardless, now we will set the state of the component, THEN set the saved data before leaving the functions

Closes #34

### CODE REVIEW

**Comment by kyrod** [comment]
Nbd right now but in the future can we try to separate concerns a bit by always creating branches off of master (or dev once we have a dev build)? So basically anytime you want to make a change, checkout+pull master first, then checkout your feature branch. it might result in conflicts occasionally but otherwise it's difficult for me to tell what was actually changed here, since i see all of your changes from #42 and then these changes over top of it

**Comment by kyrod** [comment]
For now i'll wait to review until #42 is merged

**Comment by MattGrantUMich** [comment]
For sure, my apologies on that. That's very easy to correct in the future so I'll be sure to do that from here on out.

**Review by kyrod — APPROVED** [review]
Tested and working on my machine, thanks for fixing this!

**Pull request merged**
