### PR TITLE
Initial Playlist Functionality

### PR DESCRIPTION
**Pull request by kyrod**
Adds ability to create, get, and find playlists, as well as get and modify a playlist's tracks.
Also refactors some existing functions to separate out basic header functionality.
Adds many tests for the new playlist functions.

### CODE REVIEW

**Comment by kyrod** [comment]
Closes #12 , Closes #13

**Comment by kyrod** [comment]
@MattGrantUMich  Looking to add Prettier formatting to our yarn lint command, but i don't want to cause any merge conflicts with code you have currently written, so I'll add that in a separate PR

**Review by MattGrantUMich — APPROVED** [review]
This code is clean 💯  as h'yuk! 

I also really like the extra utils added in for the testing purposes. The structure we have now is amazing imo.

**Comment by MattGrantUMich** [comment]
big well done react

**Pull request merged**
